import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ClerkProvider 
        Set-Cookies={{
          cookieOption:{
            sameSite:'Lax',
            preload:true,
            secure:true
          }
        }}>
        {children}
        </ClerkProvider>
        </body>
    </html>
  );
}
